import { Department, Doctor, Patient, Token, Queue, Notification, QueueAnalytics, Profile } from '@/types/queue';

// DEFAULT SEED DEPARTMENTS
export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-gm',
    name: 'General Medicine',
    code: 'GM',
    description: 'Primary health care, routine checkups and common ailment diagnoses.',
    average_consultation_minutes: 8,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'dept-car',
    name: 'Cardiology',
    code: 'CAR',
    description: 'Comprehensive cardiac evaluations, ECG, and cardiovascular care.',
    average_consultation_minutes: 15,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'dept-ort',
    name: 'Orthopedics',
    code: 'ORT',
    description: 'Bone, joint, spine, and musculoskeletal injury consultations.',
    average_consultation_minutes: 12,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'dept-ped',
    name: 'Pediatrics',
    code: 'PED',
    description: 'Child health, immunization, pediatric checkups, and growth assessment.',
    average_consultation_minutes: 10,
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'dept-den',
    name: 'Dental',
    code: 'DEN',
    description: 'Oral health checks, scaling, extractions, and dental procedures.',
    average_consultation_minutes: 15,
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

// DEFAULT SEED PROFILES & DOCTORS
export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-sharma',
    profile_id: 'prof-sharma',
    department_id: 'dept-gm',
    specialization: 'Senior Physician & Internal Medicine Specialist',
    room_number: 'Room 102',
    average_consultation_minutes: 8,
    is_available: true,
    created_at: new Date().toISOString(),
    profile: {
      id: 'prof-sharma',
      full_name: 'Dr. Rajesh Sharma',
      email: 'dr.sharma@hospital.org',
      phone: '+91 98765 43210',
      role: 'DOCTOR',
      created_at: new Date().toISOString(),
    },
    department: INITIAL_DEPARTMENTS[0],
  },
  {
    id: 'doc-kumar',
    profile_id: 'prof-kumar',
    department_id: 'dept-car',
    specialization: 'Consultant Cardiologist & Heart Failure Specialist',
    room_number: 'Room 205',
    average_consultation_minutes: 15,
    is_available: true,
    created_at: new Date().toISOString(),
    profile: {
      id: 'prof-kumar',
      full_name: 'Dr. Anita Kumar',
      email: 'dr.kumar@hospital.org',
      phone: '+91 98765 43211',
      role: 'DOCTOR',
      created_at: new Date().toISOString(),
    },
    department: INITIAL_DEPARTMENTS[1],
  },
  {
    id: 'doc-verma',
    profile_id: 'prof-verma',
    department_id: 'dept-ort',
    specialization: 'Orthopedic Surgeon & Joint Replacement Specialist',
    room_number: 'Room 304',
    average_consultation_minutes: 12,
    is_available: true,
    created_at: new Date().toISOString(),
    profile: {
      id: 'prof-verma',
      full_name: 'Dr. Vikram Verma',
      email: 'dr.verma@hospital.org',
      phone: '+91 98765 43212',
      role: 'DOCTOR',
      created_at: new Date().toISOString(),
    },
    department: INITIAL_DEPARTMENTS[2],
  },
  {
    id: 'doc-gupta',
    profile_id: 'prof-gupta',
    department_id: 'dept-ped',
    specialization: 'Consultant Pediatrician & Child Specialist',
    room_number: 'Room 108',
    average_consultation_minutes: 10,
    is_available: true,
    created_at: new Date().toISOString(),
    profile: {
      id: 'prof-gupta',
      full_name: 'Dr. Sunita Gupta',
      email: 'dr.gupta@hospital.org',
      phone: '+91 98765 43213',
      role: 'DOCTOR',
      created_at: new Date().toISOString(),
    },
    department: INITIAL_DEPARTMENTS[3],
  },
];

// DEFAULT PATIENTS
export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    profile_id: 'prof-pat-1',
    date_of_birth: '1990-05-15',
    gender: 'Male',
    address: '12 Hospital Road, Metro City',
    created_at: new Date().toISOString(),
    profile: {
      id: 'prof-pat-1',
      full_name: 'Rohan Mehta',
      email: 'rohan.mehta@gmail.com',
      phone: '+91 98200 11223',
      role: 'PATIENT',
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'pat-2',
    profile_id: 'prof-pat-2',
    date_of_birth: '1985-08-22',
    gender: 'Female',
    address: '45 Park Avenue, Metro City',
    created_at: new Date().toISOString(),
    profile: {
      id: 'prof-pat-2',
      full_name: 'Priya Patel',
      email: 'priya.patel@gmail.com',
      phone: '+91 98200 44556',
      role: 'PATIENT',
      created_at: new Date().toISOString(),
    },
  },
  {
    id: 'pat-3',
    profile_id: 'prof-pat-3',
    date_of_birth: '1978-11-03',
    gender: 'Male',
    address: '88 Lake View, Metro City',
    created_at: new Date().toISOString(),
    profile: {
      id: 'prof-pat-3',
      full_name: 'Amitabh Sen',
      email: 'amitabh.sen@gmail.com',
      phone: '+91 98200 77889',
      role: 'PATIENT',
      created_at: new Date().toISOString(),
    },
  },
];

const todayStr = new Date().toISOString().split('T')[0];

// INITIAL SEED TOKENS
export const INITIAL_TOKENS: Token[] = [
  {
    id: 'tok-24',
    token_number: 24,
    display_token: 'GM-024',
    patient_id: 'pat-1',
    doctor_id: 'doc-sharma',
    department_id: 'dept-gm',
    priority: 'NORMAL',
    status: 'IN_CONSULTATION',
    queue_date: todayStr,
    created_at: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    called_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    patient: INITIAL_PATIENTS[0],
    doctor: INITIAL_DOCTORS[0],
    department: INITIAL_DEPARTMENTS[0],
  },
  {
    id: 'tok-25',
    token_number: 25,
    display_token: 'GM-025',
    patient_id: 'pat-2',
    doctor_id: 'doc-sharma',
    department_id: 'dept-gm',
    priority: 'NORMAL',
    status: 'WAITING',
    queue_date: todayStr,
    created_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    patient: INITIAL_PATIENTS[1],
    doctor: INITIAL_DOCTORS[0],
    department: INITIAL_DEPARTMENTS[0],
  },
  {
    id: 'tok-26',
    token_number: 26,
    display_token: 'GM-026',
    patient_id: 'pat-3',
    doctor_id: 'doc-sharma',
    department_id: 'dept-gm',
    priority: 'PRIORITY',
    status: 'WAITING',
    queue_date: todayStr,
    created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    patient: INITIAL_PATIENTS[2],
    doctor: INITIAL_DOCTORS[0],
    department: INITIAL_DEPARTMENTS[0],
  },
  {
    id: 'tok-27',
    token_number: 27,
    display_token: 'GM-027',
    patient_id: 'pat-1',
    doctor_id: 'doc-sharma',
    department_id: 'dept-gm',
    priority: 'NORMAL',
    status: 'WAITING',
    queue_date: todayStr,
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    patient: INITIAL_PATIENTS[0],
    doctor: INITIAL_DOCTORS[0],
    department: INITIAL_DEPARTMENTS[0],
  },
  {
    id: 'tok-28',
    token_number: 28,
    display_token: 'GM-028',
    patient_id: 'pat-2',
    doctor_id: 'doc-sharma',
    department_id: 'dept-gm',
    priority: 'NORMAL',
    status: 'WAITING',
    queue_date: todayStr,
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    patient: INITIAL_PATIENTS[1],
    doctor: INITIAL_DOCTORS[0],
    department: INITIAL_DEPARTMENTS[0],
  },
  {
    id: 'tok-29',
    token_number: 29,
    display_token: 'GM-029',
    patient_id: 'pat-3',
    doctor_id: 'doc-sharma',
    department_id: 'dept-gm',
    priority: 'NORMAL',
    status: 'WAITING',
    queue_date: todayStr,
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    patient: INITIAL_PATIENTS[2],
    doctor: INITIAL_DOCTORS[0],
    department: INITIAL_DEPARTMENTS[0],
  },
];

// INITIAL QUEUE RECORD
export const INITIAL_QUEUES: Queue[] = [
  {
    id: 'q-gm',
    department_id: 'dept-gm',
    doctor_id: 'doc-sharma',
    queue_date: todayStr,
    current_token_id: 'tok-24',
    is_paused: false,
    created_at: new Date().toISOString(),
    department: INITIAL_DEPARTMENTS[0],
    doctor: INITIAL_DOCTORS[0],
    current_token: INITIAL_TOKENS[0],
  },
  {
    id: 'q-car',
    department_id: 'dept-car',
    doctor_id: 'doc-kumar',
    queue_date: todayStr,
    current_token_id: null,
    is_paused: false,
    created_at: new Date().toISOString(),
    department: INITIAL_DEPARTMENTS[1],
    doctor: INITIAL_DOCTORS[1],
  },
];
